// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class GenreMovie3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreMovie3));
        
        string IMigrationMetadata.Id
        {
            get { return "202002112115221_GenreMovie3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
